# Laboratorio 5 - Parte 1

### Máquinas de Vectores de Soporte

### 2018-II

#### Profesor: Julián D. Arias Londoño
#### julian.ariasl@udea.edu.co


## Guía del laboratorio

En esta archivo va a encontrar tanto celdas de código cómo celdas de texto con las instrucciones para desarrollar el laboratorio.

Lea atentamente las instrucciones entregadas en las celdas de texto correspondientes y proceda con la solución de las preguntas planteadas.

Nota: no olvide ir ejecutando las celdas de código de arriba hacia abajo para que no tenga errores de importación de librerías o por falta de definición de variables.

#### Primer Integrante: Daniel Santa Rendón

#### Documento: 1040050021


#### Segundo Integrante: Daniel Torres González

#### Documento: 1020492000

In [1]:
from __future__ import division
import numpy as np
import math
import matplotlib.pyplot as plt
#Algunas advertencias que queremos evitar
import warnings
warnings.filterwarnings("always")
%matplotlib inline

## Ejercicio 1

En este ejercicio deben resolver un problema de clasificación multi-clase usando una SVM. Teniendo en cuenta que la formulación original de la SVM sólo permite resolver problemas bi-clase, deben comparar los resultados obtenidos usando una estrategia **Uno vs Uno** con una estrategia **Uno vs El resto**.

Cargamos los datos:

In [2]:
from sklearn.datasets import load_digits
from sklearn.decomposition import PCA
digits = load_digits(n_class=4)

#--------- preprocesamiento--------------------
pca = PCA(0.99, whiten=True)
data = pca.fit_transform(digits.data)

#---------- Datos a usar ----------------------
X = data
Y = digits.target

C:\Users\ALEJO\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\Users\ALEJO\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\Users\ALEJO\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\Users\ALEJO\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\Users\ALEJO\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 19

C:\Users\ALEJO\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\Users\ALEJO\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


Consutar el manejo de la librería sklearn para entrenar un modelos SVM en: http://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html#sklearn.svm.SVC. Para el caso multiclase la librería ya tiene implementada la estrategia **Uno vs Uno**, así que en este caso sólo deben llamar correctamente los métodos. Complete el siguiente código usando un clasificador basado en SVM:

In [3]:
import math
import numpy as np
from numpy import random
from sklearn.svm import SVC
from sklearn import preprocessing
from sklearn.model_selection import StratifiedKFold


#Validamos el modelo
Folds = 4
random.seed(19680801)
EficienciaTrain = np.zeros(Folds)
EficienciaVal = np.zeros(Folds)
PorcentajeVS = np.zeros(Folds)
skf = StratifiedKFold(n_splits=Folds)
modelo = SVC(gamma='auto', C=1,  kernel='linear', decision_function_shape='ovo', probability = True)
j = 0
for train, test in skf.split(X, Y):
    Xtrain = X[train,:]
    Ytrain = Y[train]
    Xtest = X[test,:]
    Ytest = Y[test]
    
    #Normalizamos los datos
    scaler = preprocessing.StandardScaler().fit(Xtrain)
    Xtrain = scaler.transform(Xtrain)
    Xtest = scaler.transform(Xtest)
    
    #Haga el llamado a la función para crear y entrenar el modelo usando los datos de entrenamiento
    modelo = SVC(gamma='auto', C=1,  kernel='linear', decision_function_shape='ovo')
    modelo.fit(Xtrain, Ytrain)
    
    
    #Validación
    Ytrain_pred = modelo.predict(Xtrain)
    Yest = modelo.predict(Xtest)
    
    PorcentajeVS[j] = modelo.support_vectors_.shape[0] / Xtrain.shape[0]
    
    #Evaluamos las predicciones del modelo con los datos de test
    EficienciaTrain[j] = np.mean(Ytrain_pred.ravel() == Ytrain.ravel())
    EficienciaVal[j] = np.mean(Yest.ravel() == Ytest.ravel())
    TotalVS = np.mean(PorcentajeVS)
    j += 1
        
print('Eficiencia durante el entrenamiento = ' + str(np.mean(EficienciaTrain)) + '+-' + str(np.std(EficienciaTrain)))
print('Eficiencia durante la validación = ' + str(np.mean(EficienciaVal)) + '+-' + str(np.std(EficienciaVal)))

Eficiencia durante el entrenamiento = 1.0+-0.0
Eficiencia durante la validación = 0.9707771243055832+-0.015485734683194906


In [4]:
import math
import numpy as np
from numpy import random
from sklearn.svm import SVC
from sklearn import preprocessing
from sklearn.model_selection import StratifiedKFold

def prueba(ker, C, gam):
    
    if ker == 'lineal':
        ker = 'linear'
    
    if gam == 0:
        gam = 'auto'
    
    #Validamos el modelo
    Folds = 4
    random.seed(19680801)
    EficienciaTrain = np.zeros(Folds)
    EficienciaVal = np.zeros(Folds)
    PorcentajeVS = np.zeros(Folds)
    skf = StratifiedKFold(n_splits=Folds)
    j = 0
    for train, test in skf.split(X, Y):
        Xtrain = X[train,:]
        Ytrain = Y[train]
        Xtest = X[test,:]
        Ytest = Y[test]

        #Normalizamos los datos
        scaler = preprocessing.StandardScaler().fit(Xtrain)
        Xtrain = scaler.transform(Xtrain)
        Xtest = scaler.transform(Xtest)

        #Haga el llamado a la función para crear y entrenar el modelo usando los datos de entrenamiento
        modelo = SVC(gamma=gam, C=float(C),  kernel=ker, decision_function_shape='ovo' , probability = True)
        modelo.fit(Xtrain, Ytrain)
  
        #Validación
        Ytrain_pred = modelo.predict(Xtrain)
        Yest = modelo.predict(Xtest)
        
        #Vectores de soporte
        PorcentajeVS[j] = modelo.support_vectors_.shape[0] / Xtrain.shape[0]
        
        #Evaluamos las predicciones del modelo con los datos de test
        EficienciaTrain[j] = np.mean(Ytrain_pred.ravel() == Ytrain.ravel())
        EficienciaVal[j] = np.mean(Yest.ravel() == Ytest.ravel())
        j += 1
        
        ETM = np.mean(EficienciaTrain)
        ETVS = np.std(EficienciaTrain)
        EVM = np.mean(EficienciaVal)
        EVST = np.std(EficienciaVal)
        TotalVS = np.mean(PorcentajeVS)
    
    return ETM, ETVS, EVM, EVST, TotalVS

Realice los experimientos necesarios para llenar la siguiente tabla:

In [5]:
import pandas as pd
import qgrid
df_types = pd.DataFrame({
    'Kernel' : pd.Series(['lineal','lineal','lineal','lineal','lineal','lineal','rbf','rbf','rbf','rbf','rbf','rbf','rbf','rbf','rbf','rbf','rbf','rbf','rbf','rbf','rbf','rbf','rbf','rbf']),
    'C' : pd.Series([0.001,0.01,0.1,1,10,100,0.001,0.001,0.001,0.01,0.01,0.01,0.1,0.1,0.1,1,1,1,10,10,10,100,100,100]),
    'gamma' : pd.Series([0,0,0,0,0,0,0.01,0.1,1,0.01,0.1,1,0.01,0.1,1,0.01,0.1,1,0.01,0.1,1,0.01,0.1,1])})
df_types["Eficiencia en validacion"] = ""
df_types["Intervalo de confianza"] = ""
df_types["% de Vectores de Soporte"] = ""
df_types.set_index(['Kernel','C','gamma'], inplace=True)


for i in df_types.index:
    
    ETM, ETVS, EVM, EVST, TotalVS = prueba(i[0], i[1], i[2])
    
    df_types["Eficiencia en validacion"][i] = EVM
    df_types["Intervalo de confianza"][i] = EVST
    df_types["% de Vectores de Soporte"][i] = TotalVS


qgrid_widget = qgrid.show_grid(df_types, show_toolbar=False)

C:\Users\ALEJO\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\Users\ALEJO\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\Users\ALEJO\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\Users\ALEJO\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\Users\ALEJO\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 19

Ejecute la siguiente instrucción para dejar guardados en el notebook los resultados de las pruebas.

In [6]:
qgrid_widget.get_changed_df()

Eficiencia en validacion Intervalo de confianza  \
Kernel C       gamma                                                   
lineal 0.001   0.00                  0.796001              0.0532963   
       0.010   0.00                  0.970699              0.0292647   
       0.100   0.00                  0.980446              0.0166111   
       1.000   0.00                  0.970777              0.0154857   
       10.000  0.00                  0.970777              0.0154857   
       100.000 0.00                  0.970777              0.0154857   
rbf    0.001   0.01                  0.315623               0.108064   
               0.10                  0.277914              0.0427515   
               1.00                  0.254171             0.00171694   
       0.010   0.01                  0.315623               0.108064   
               0.10                  0.277914              0.0427515   
               1.00                  0.254171             0.00171694   
       0.100   0.01                  0.832031              0.0364481   
               0.10                  0.277914              0.0427515   
               1.00                  0.254171             0.00171694   
       1.000   0.01                  0.984659              0.0115213   
               0.10                  0.808549              0.0407067   
               1.00                  0.256964             0.00648594   
       10.000  0.01                  0.990246             0.00831727   
               0.10                  0.815471              0.0376978   
               1.00                  0.258369             0.00602608   
       100.000 0.01                  0.990246             0.00831727   
               0.10                  0.815471              0.0376978   
               1.00                  0.258369             0.00602608   

                     % de Vectores de Soporte  
Kernel C       gamma                           
lineal 0.001   0.00                         1  
       0.010   0.00                  0.608322  
       0.100   0.00                  0.286595  
       1.000   0.00                  0.262038  
       10.000  0.00                  0.262038  
       100.000 0.00                  0.262038  
rbf    0.001   0.01                         1  
               0.10                         1  
               1.00                  0.999539  
       0.010   0.01                         1  
               0.10                         1  
               1.00                         1  
       0.100   0.01                         1  
               0.10                         1  
               1.00                         1  
       1.000   0.01                  0.643049  
               0.10                  0.972674  
               1.00                         1  
       10.000  0.01                  0.577322  
               0.10                  0.972213  
               1.00                         1  
       100.000 0.01                  0.577322  
               0.10                  0.972213  
               1.00                         1

## Ejercicio 2

Cree dos funciones, una para entrenar un conjunto de modelos bajo la estrategia Uno vs el resto, usando como clasificador base una SVM. La segunda función debe usar el conjunto de modelos entrenados, y clasificar un conjunto de muestras de validación.

In [60]:
def TrainSVM_OnevsRest(kernel, C , gamma, X_train, Y_train):
    n_classes = np.unique(Y_train).size
    Y_aux = np.zeros(len(Y_train))
    modelos = []
    for i in range(0, n_classes):
        Y_aux[Y_train == i] = 1
        #Y_aux[(Y_aux != i) & (Y_aux != -1)] = 0
        Y_aux[Y_train != i] = -1
      
        clf = SVC(C=C, kernel=kernel, gamma=gamma, probability = True)
        clf.fit(X_train, Y_aux)
        modelos.append(clf)
    
    return modelos

In [76]:
def ValidaSVM_OnevsRest2(Xtrain, Xtest, modelos):

    aux_ProbsTrain = []
    aux_ProbsTest = []
    p = 0
    for k in modelos:
        probsTest = k.predict_proba(Xtest)
        probsTrain = k.predict_proba(Xtrain)
        i = 0
        Yest2 = []
        Ytrain_predict2 = []

        for i in range (len(probsTrain)):
            aux_ProbsTrain[p].append(np.argmax(probsTrain[[i], :]))

        for j in range (len(probsTest)):
            aux_ProbsTest[p].append(np.argmax(probsTest[[j], :]))           
        p += 1
    
    Ytrain_predict2 = np.argmax(aux_ProbsTrain)
    Yest2 = np.argmax(Yest2)
    return np.asarray(Ytrain_predict2),np.asarray(Yest2)

In [79]:
def ValidaSVM_OnevsRest(modelos,datos):
    preds=[]
    for i in datos:
        predicciones_modelos=[]
        for k in modelos:
            prob = k.predict_proba([i])
            preds_modelos.append(prob[0][1])
            
        modelo=np.argmax(preds_modelos)
        preds.append(modelo)
        
    return preds

## Ejercicio 3

Use las funciones definidas en el punto anterior para llevar a cabo la prueba de simulación con el mismo conjunto de datos del punto 1.

In [92]:
def prueba2(ker, C, gam):
    
    if ker == 'lineal':
        ker = 'linear'
    
    if gam == 0:
        gam = 'auto'
    
    #Validamos el modelo
    Folds = 4
    random.seed(19680801)
    EficienciaTrain = np.zeros(Folds)
    EficienciaVal = np.zeros(Folds)
    PorcentajeVS = np.zeros(Folds)
    skf = StratifiedKFold(n_splits=Folds)
    j = 0
    for train, test in skf.split(X, Y):
        Xtrain = X[train,:]
        Ytrain = Y[train]
        Xtest = X[test,:]
        Ytest = Y[test]

        #Normalizamos los datos
        scaler = preprocessing.StandardScaler().fit(Xtrain)
        Xtrain = scaler.transform(Xtrain)
        Xtest = scaler.transform(Xtest)

        #Haga el llamado a la función para crear y entrenar el modelo usando los datos de entrenamiento
        modelos = TrainSVM_OnevsRest(ker, C, gam, Xtrain, Ytrain)
        #modelo.fit(Xtrain, Ytrain)
        
        #Validación
        Ytrain_pred = ValidaSVM_OnevsRest(modelos,Xtrain)
        Yest = ValidaSVM_OnevsRest(modelos,Xtest)
        
        #Vectores de soporte

        
        #TotalVS = np.mean(nroVectoresDeSoporte)
        TotalVs = 0
        
        #Evaluamos las predicciones del modelo con los datos de test
        EficienciaTrain[j] = np.mean(np.array(Ytrain_pred).ravel() == Ytrain.ravel())
        EficienciaVal[j] = np.mean(np.array(Yest).ravel() == Ytest.ravel())
        PorcentajeVS[j]=0
        for modelo in modelos:
            PorcentajeVS[j] = PorcentajeVS[j] + (modelo.support_vectors_.shape[0])/Xtrain.shape[0]
        j += 1
        
        
        ETM = np.mean(EficienciaTrain)
        ETVS = np.std(EficienciaTrain)
        EVM = np.mean(EficienciaVal)
        EVST = np.std(EficienciaVal)
        TotalVS = np.mean(PorcentajeVS)
    
    return ETM, ETVS, EVM, EVST, TotalVS

Realice los experimientos necesarios para llenar la siguiente tabla:

In [93]:
import pandas as pd
import qgrid
df_types = pd.DataFrame({
    'Kernel' : pd.Series(['lineal','lineal','lineal','lineal','lineal','lineal','rbf','rbf','rbf','rbf','rbf','rbf','rbf','rbf','rbf','rbf','rbf','rbf','rbf','rbf','rbf','rbf','rbf','rbf']),
    'C' : pd.Series([0.001,0.01,0.1,1,10,100,0.001,0.001,0.001,0.01,0.01,0.01,0.1,0.1,0.1,1,1,1,10,10,10,100,100,100]),
    'gamma' : pd.Series([0,0,0,0,0,0,0.01,0.1,1,0.01,0.1,1,0.01,0.1,1,0.01,0.1,1,0.01,0.1,1,0.01,0.1,1])})
df_types["Eficiencia en validacion"] = ""
df_types["Intervalo de confianza"] = ""
df_types["% de Vectores de Soporte"] = ""
df_types.set_index(['Kernel','C','gamma'], inplace=True)

for i in df_types.index:
    
    ETM, ETVS, EVM, EVST, TotalVS = prueba2(i[0], i[1], i[2])
    
    df_types["Eficiencia en validacion"][i] = EVM
    df_types["Intervalo de confianza"][i] = EVST
    df_types["% de Vectores de Soporte"][i] = TotalVS

qgrid_widget = qgrid.show_grid(df_types, show_toolbar=False)

Ejecute la siguiente instrucción para dejar guardados en el notebook los resultados de las pruebas.

In [94]:
qgrid_widget.get_changed_df()

Eficiencia en validacion Intervalo de confianza  \
Kernel C       gamma                                                   
lineal 0.001   0.00                  0.953931              0.0393175   
       0.010   0.00                  0.962296              0.0345664   
       0.100   0.00                  0.974928               0.020473   
       1.000   0.00                  0.977737              0.0163723   
       10.000  0.00                  0.977737              0.0163723   
       100.000 0.00                  0.977737              0.0163723   
rbf    0.001   0.01                  0.963731              0.0319974   
               0.10                   0.96536              0.0150895   
               1.00                  0.282074              0.0156085   
       0.010   0.01                  0.963692              0.0343907   
               0.10                  0.926598              0.0343027   
               1.00                  0.251377             0.00326241   
       0.100   0.01                  0.963692              0.0343907   
               0.10                  0.925217               0.033649   
               1.00                  0.251377             0.00326241   
       1.000   0.01                  0.981827              0.0188344   
               0.10                  0.932162                0.03387   
               1.00                  0.251377             0.00326241   
       10.000  0.01                  0.988841              0.0105271   
               0.10                  0.940442              0.0294477   
               1.00                  0.251377             0.00326241   
       100.000 0.01                  0.988841              0.0105271   
               0.10                  0.940442              0.0294477   
               1.00                  0.251377             0.00326241   

                     % de Vectores de Soporte  
Kernel C       gamma                           
lineal 0.001   0.00                   2.09908  
       0.010   0.00                   1.18106  
       0.100   0.00                  0.416675  
       1.000   0.00                  0.277791  
       10.000  0.00                  0.277791  
       100.000 0.00                  0.277791  
rbf    0.001   0.01                   2.00556  
               0.10                   2.02732  
               1.00                   2.64582  
       0.010   0.01                   2.17544  
               0.10                   3.89069  
               1.00                         4  
       0.100   0.01                   2.21386  
               0.10                    3.9194  
               1.00                         4  
       1.000   0.01                   1.37363  
               0.10                   3.88049  
               1.00                         4  
       10.000  0.01                   1.11017  
               0.10                   3.86754  
               1.00                         4  
       100.000 0.01                   1.11017  
               0.10                   3.86754  
               1.00                         4

*En las tablas el punto separa las cifras decimales, es decir 100.000 es 100 ó 1.000 es 1.